name: Fetch Police Alerts

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-alerts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Fetch Police Alerts
      run: |
        curl -X POST "https://atlmbgnawococyysdtpr.supabase.co/functions/v1/fetch-police-alerts" \
          -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0bG1iZ25hd29jb2N5eXNkdHByIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NDAwMzkyMSwiZXhwIjoyMDY5NTc5OTIxfQ.jJ4xbDHyPlBdaCR-rnzPhVSBSajtWlmdaN2VUp5rffM" \
          -H "Content-Type: application/json"
      
    - name: Log Result
      run: echo "Police alerts fetch completed at $(date)" 